### PR TITLE
Extension schema for Docker

### PR DESCRIPTION
**Pull request by wmunyan**
Added a number of tests and supporting information in order to assess the configuration of Docker containers/images.
- The "execps_test" mirrors the output of the unix "process58_test", but within a docker container/image
- The "info_test" examines a "flattened" output from the "docker info" command
- The "keyedinfo_test" examines the full hierarchical output from the "docker info" command
- The "inspect_test" examines the output of the "docker inspect" command
- The "process_test" examines the output of the "docker ps" command
- The "version_test" examines the output of the "docker version" command

### CODE REVIEW

**Comment by mpreisler** [comment]
To create 3 separate PRs you need to create 3 separate branches and pull request them all separately. Otherwise commits unrelated to the PR are going to show up in it, as is the case here.

**Comment by wmunyan** [comment]
Here's what I thought I had done:
The initial PR was created, and included both the SUSE and ShellCommand schemas.
I closed that PR with the intent of creating separate branches.
I created a separate branch, added the SUSE schema and created a PR
I created yet another branch for the Docker schema and created this PR
The commits I thought reflected the removal of the original SUSE/ShellCommand combinations
The only files changed in this PR are the additions of the Docker schema.
Do i need to re-fork the sandbox and re-add everything again?
Here's my Git Novice showing up.  My apologies
-B

**Comment by mpreisler** [comment]
Hmm,
having a commit that removes changes would create a very messy history. I recommend squashing it and making sure your branch is based on `origin/master`. Check out http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Or you can do `git reset --hard origin/master` and reapply only the commits you need in this PR.

**Comment by wmunyan** [comment]
Thanks Martin.  I'll get it figured out and re-PR'd

**Pull request closed without merging**
